// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "payload_bp.h"

void BpFieldDescriptorsInitPayloadPacket(struct PayloadPacket *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->cur_time), BpUint(32, sizeof(uint32_t)), "cur_time");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->gps_lat), BpInt(32, sizeof(int32_t)), "gps_lat");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->gps_lng), BpInt(32, sizeof(int32_t)), "gps_lng");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->gps_alt), BpInt(32, sizeof(int32_t)), "gps_alt");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->velocity), BpUint(32, sizeof(uint32_t)), "velocity");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->accel_x), BpUint(32, sizeof(uint32_t)), "accel_x");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->accel_y), BpUint(32, sizeof(uint32_t)), "accel_y");
    fds[7] = BpMessageFieldDescriptor((void *)&(m->accel_z), BpUint(32, sizeof(uint32_t)), "accel_z");
    fds[8] = BpMessageFieldDescriptor((void *)&(m->distance_to_target), BpUint(32, sizeof(uint32_t)), "distance_to_target");
    fds[9] = BpMessageFieldDescriptor((void *)&(m->destination_reached), BpBool(), "destination_reached");
}

void BpXXXProcessPayloadPacket(void *data, struct BpProcessorContext *ctx) {
    struct PayloadPacket *m = (struct PayloadPacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[10];
    BpFieldDescriptorsInitPayloadPacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 10, 289, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPayloadPacket(void *data, struct BpJsonFormatContext *ctx) {
    struct PayloadPacket *m = (struct PayloadPacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[10];
    BpFieldDescriptorsInitPayloadPacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 10, 289, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePayloadPacket(struct PayloadPacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPayloadPacket((void *)m, &ctx);
    return 0;
}

int DecodePayloadPacket(struct PayloadPacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPayloadPacket((void *)m, &ctx);
    return 0;
}

int JsonPayloadPacket(struct PayloadPacket *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPayloadPacket((void *)m, &ctx);
    return ctx.n;
}