// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__PAYLOAD_BP_H__
#define __BITPROTO__PAYLOAD_BP_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct PayloadPacket
#define BYTES_LENGTH_PAYLOAD_PACKET 37

// Payload telemetry - subset of flight computer fields plus payload-specific fields
struct PayloadPacket {
    // 1. Time
    uint32_t cur_time; // 32bit
    // 2. GPS (shared with flight computer)
    int32_t gps_lat; // 32bit
    // Scaled by 10^7
    int32_t gps_lng; // 32bit
    // Scaled by 10^7
    int32_t gps_alt; // 32bit
    // 3. Motion (subset)
    uint32_t velocity; // 32bit
    // IEEE 754 float as uint32
    uint32_t accel_x; // 32bit
    // IEEE 754 float as uint32
    uint32_t accel_y; // 32bit
    // IEEE 754 float as uint32
    uint32_t accel_z; // 32bit
    // 4. Payload-specific fields
    uint32_t distance_to_target; // 32bit
    // IEEE 754 float as uint32, meters
    bool destination_reached; // 1bit
};

// Encode struct PayloadPacket to given buffer s.
int EncodePayloadPacket(struct PayloadPacket *m, unsigned char *s);
// Decode struct PayloadPacket from given buffer s.
int DecodePayloadPacket(struct PayloadPacket *m, unsigned char *s);
// Format struct PayloadPacket to a json format string.
int JsonPayloadPacket(struct PayloadPacket *m, char *s);

void BpXXXProcessPayloadPacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPayloadPacket(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif