# Code generated by bitproto. DO NOT EDIT.


import json
from dataclasses import dataclass, field
from typing import ClassVar, Dict, List, Union
from enum import IntEnum, unique

from bitprotolib import bp


@dataclass
class PayloadPacket(bp.MessageBase):
    """
    Payload telemetry - subset of flight computer fields plus payload-specific fields
    """
    # Number of bytes to serialize class PayloadPacket
    BYTES_LENGTH: ClassVar[int] = 37

    # 1. Time
    cur_time: int = 0 # 32bit
    # 2. GPS (shared with flight computer)
    gps_lat: int = 0 # 32bit
    # Scaled by 10^7
    gps_lng: int = 0 # 32bit
    # Scaled by 10^7
    gps_alt: int = 0 # 32bit
    # 3. Motion (subset)
    velocity: int = 0 # 32bit
    # IEEE 754 float as uint32
    accel_x: int = 0 # 32bit
    # IEEE 754 float as uint32
    accel_y: int = 0 # 32bit
    # IEEE 754 float as uint32
    accel_z: int = 0 # 32bit
    # 4. Payload-specific fields
    distance_to_target: int = 0 # 32bit
    # IEEE 754 float as uint32, meters
    destination_reached: bool = False # 1bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, bp.Uint(32)),
            bp.MessageFieldProcessor(2, bp.Int(32)),
            bp.MessageFieldProcessor(3, bp.Int(32)),
            bp.MessageFieldProcessor(4, bp.Int(32)),
            bp.MessageFieldProcessor(5, bp.Uint(32)),
            bp.MessageFieldProcessor(6, bp.Uint(32)),
            bp.MessageFieldProcessor(7, bp.Uint(32)),
            bp.MessageFieldProcessor(8, bp.Uint(32)),
            bp.MessageFieldProcessor(9, bp.Uint(32)),
            bp.MessageFieldProcessor(10, bp.Bool()),
        ]
        return bp.MessageProcessor(False, 289, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 1:
            self.cur_time |= (int(b) << lshift)
        if di.field_number == 2:
            self.gps_lat |= bp.int32((int(b) << lshift))
        if di.field_number == 3:
            self.gps_lng |= bp.int32((int(b) << lshift))
        if di.field_number == 4:
            self.gps_alt |= bp.int32((int(b) << lshift))
        if di.field_number == 5:
            self.velocity |= (int(b) << lshift)
        if di.field_number == 6:
            self.accel_x |= (int(b) << lshift)
        if di.field_number == 7:
            self.accel_y |= (int(b) << lshift)
        if di.field_number == 8:
            self.accel_z |= (int(b) << lshift)
        if di.field_number == 9:
            self.distance_to_target |= (int(b) << lshift)
        if di.field_number == 10:
            self.destination_reached = bool(b)
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 1:
            return (self.cur_time >> rshift) & 255
        if di.field_number == 2:
            return (self.gps_lat >> rshift) & 255
        if di.field_number == 3:
            return (self.gps_lng >> rshift) & 255
        if di.field_number == 4:
            return (self.gps_alt >> rshift) & 255
        if di.field_number == 5:
            return (self.velocity >> rshift) & 255
        if di.field_number == 6:
            return (self.accel_x >> rshift) & 255
        if di.field_number == 7:
            return (self.accel_y >> rshift) & 255
        if di.field_number == 8:
            return (self.accel_z >> rshift) & 255
        if di.field_number == 9:
            return (self.distance_to_target >> rshift) & 255
        if di.field_number == 10:
            return (int(self.destination_reached) >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return