# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x10rocket_telemetry\"\xda\x04\n\x0fTelemetryPacket\x12\x10\n\x08\x63ur_time\x18\x01 \x01(\r\x12\x0f\n\x07gps_lat\x18\x02 \x01(\x05\x12\x0f\n\x07gps_lng\x18\x03 \x01(\x05\x12\x0f\n\x07gps_alt\x18\x04 \x01(\x05\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x05 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x06 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x07 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x08 \x01(\x02\x12\x0e\n\x06gyro_y\x18\t \x01(\x02\x12\x0e\n\x06gyro_z\x18\n \x01(\x02\x12\x10\n\x08hg_accel\x18\x0b \x01(\x02\x12\x10\n\x08\x61lt_baro\x18\x0c \x01(\x02\x12\x14\n\x0cvel_vertical\x18\r \x01(\x02\x12\x12\n\nsmooth_vel\x18\x0e \x01(\x02\x12\r\n\x05press\x18\x0f \x01(\x02\x12\x0c\n\x04temp\x18\x10 \x01(\x02\x12\x16\n\x0elaunchsite_msl\x18\x11 \x01(\x02\x12\x15\n\rairbrake_cont\x18\x12 \x01(\x08\x12\x14\n\x0c\x61\x62_servo_pct\x18\x13 \x01(\x02\x12\x16\n\x0e\x63nrd_servo_pct\x18\x14 \x01(\x02\x12\x1a\n\x12\x64rogue_pyro_cont_1\x18\x15 \x01(\x08\x12\x1a\n\x12\x64rogue_pyro_cont_2\x18\x16 \x01(\x08\x12\x18\n\x10main_pyro_cont_1\x18\x17 \x01(\x08\x12\x18\n\x10main_pyro_cont_2\x18\x18 \x01(\x08\x12\x14\n\x0c\x66light_index\x18\x19 \x01(\x05\x12\x12\n\nellipse_on\x18\x1a \x01(\x08\x12\x12\n\ncameras_on\x18\x1b \x01(\x08\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x1c \x01(\x02\x12\x14\n\x0c\x66light_stage\x18\x1d \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYPACKET']._serialized_start=38
  _globals['_TELEMETRYPACKET']._serialized_end=640
# @@protoc_insertion_point(module_scope)
