# Code generated by bitproto. DO NOT EDIT.


import json
from dataclasses import dataclass, field
from typing import ClassVar, Dict, List, Union
from enum import IntEnum, unique

from bitprotolib import bp


@dataclass
class TelemetryPacket(bp.MessageBase):
    # Number of bytes to serialize class TelemetryPacket
    BYTES_LENGTH: ClassVar[int] = 89

    # 1. Time
    cur_time: int = 0 # 32bit
    # 2. GPS
    gps_lat: int = 0 # 32bit
    # Scaled by 10^7
    gps_lng: int = 0 # 32bit
    # Scaled by 10^7
    gps_alt: int = 0 # 32bit
    accel_x: int = 0 # 32bit
    accel_y: int = 0 # 32bit
    accel_z: int = 0 # 32bit
    gyro_x: int = 0 # 32bit
    gyro_y: int = 0 # 32bit
    gyro_z: int = 0 # 32bit
    hg_accel: int = 0 # 32bit
    # 4. Flight Data
    alt_baro: int = 0 # 32bit
    vel_vertical: int = 0 # 32bit
    smooth_vel: int = 0 # 32bit
    press: int = 0 # 32bit
    temp: int = 0 # 32bit
    launchsite_msl: int = 0 # 32bit
    # 5. Servos & Continuity
    airbrake_cont: bool = False # 1bit
    ab_servo_pct: int = 0 # 32bit
    cnrd_servo_pct: int = 0 # 32bit
    drogue_pyro_cont_1: bool = False # 1bit
    drogue_pyro_cont_2: bool = False # 1bit
    main_pyro_cont_1: bool = False # 1bit
    main_pyro_cont_2: bool = False # 1bit
    # 6. State & Status
    flight_index: int = 0 # 32bit
    ellipse_on: bool = False # 1bit
    cameras_on: bool = False # 1bit
    battery_voltage: int = 0 # 32bit
    flight_stage: int = 0 # 32bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, bp.Uint(32)),
            bp.MessageFieldProcessor(2, bp.Int(32)),
            bp.MessageFieldProcessor(3, bp.Int(32)),
            bp.MessageFieldProcessor(4, bp.Int(32)),
            bp.MessageFieldProcessor(5, bp.Uint(32)),
            bp.MessageFieldProcessor(6, bp.Uint(32)),
            bp.MessageFieldProcessor(7, bp.Uint(32)),
            bp.MessageFieldProcessor(8, bp.Uint(32)),
            bp.MessageFieldProcessor(9, bp.Uint(32)),
            bp.MessageFieldProcessor(10, bp.Uint(32)),
            bp.MessageFieldProcessor(11, bp.Uint(32)),
            bp.MessageFieldProcessor(12, bp.Uint(32)),
            bp.MessageFieldProcessor(13, bp.Uint(32)),
            bp.MessageFieldProcessor(14, bp.Uint(32)),
            bp.MessageFieldProcessor(15, bp.Uint(32)),
            bp.MessageFieldProcessor(16, bp.Uint(32)),
            bp.MessageFieldProcessor(17, bp.Uint(32)),
            bp.MessageFieldProcessor(18, bp.Bool()),
            bp.MessageFieldProcessor(19, bp.Uint(32)),
            bp.MessageFieldProcessor(20, bp.Uint(32)),
            bp.MessageFieldProcessor(21, bp.Bool()),
            bp.MessageFieldProcessor(22, bp.Bool()),
            bp.MessageFieldProcessor(23, bp.Bool()),
            bp.MessageFieldProcessor(24, bp.Bool()),
            bp.MessageFieldProcessor(25, bp.Int(32)),
            bp.MessageFieldProcessor(26, bp.Bool()),
            bp.MessageFieldProcessor(27, bp.Bool()),
            bp.MessageFieldProcessor(28, bp.Uint(32)),
            bp.MessageFieldProcessor(29, bp.Int(32)),
        ]
        return bp.MessageProcessor(False, 711, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 1:
            self.cur_time |= (int(b) << lshift)
        if di.field_number == 2:
            self.gps_lat |= bp.int32((int(b) << lshift))
        if di.field_number == 3:
            self.gps_lng |= bp.int32((int(b) << lshift))
        if di.field_number == 4:
            self.gps_alt |= bp.int32((int(b) << lshift))
        if di.field_number == 5:
            self.accel_x |= (int(b) << lshift)
        if di.field_number == 6:
            self.accel_y |= (int(b) << lshift)
        if di.field_number == 7:
            self.accel_z |= (int(b) << lshift)
        if di.field_number == 8:
            self.gyro_x |= (int(b) << lshift)
        if di.field_number == 9:
            self.gyro_y |= (int(b) << lshift)
        if di.field_number == 10:
            self.gyro_z |= (int(b) << lshift)
        if di.field_number == 11:
            self.hg_accel |= (int(b) << lshift)
        if di.field_number == 12:
            self.alt_baro |= (int(b) << lshift)
        if di.field_number == 13:
            self.vel_vertical |= (int(b) << lshift)
        if di.field_number == 14:
            self.smooth_vel |= (int(b) << lshift)
        if di.field_number == 15:
            self.press |= (int(b) << lshift)
        if di.field_number == 16:
            self.temp |= (int(b) << lshift)
        if di.field_number == 17:
            self.launchsite_msl |= (int(b) << lshift)
        if di.field_number == 18:
            self.airbrake_cont = bool(b)
        if di.field_number == 19:
            self.ab_servo_pct |= (int(b) << lshift)
        if di.field_number == 20:
            self.cnrd_servo_pct |= (int(b) << lshift)
        if di.field_number == 21:
            self.drogue_pyro_cont_1 = bool(b)
        if di.field_number == 22:
            self.drogue_pyro_cont_2 = bool(b)
        if di.field_number == 23:
            self.main_pyro_cont_1 = bool(b)
        if di.field_number == 24:
            self.main_pyro_cont_2 = bool(b)
        if di.field_number == 25:
            self.flight_index |= bp.int32((int(b) << lshift))
        if di.field_number == 26:
            self.ellipse_on = bool(b)
        if di.field_number == 27:
            self.cameras_on = bool(b)
        if di.field_number == 28:
            self.battery_voltage |= (int(b) << lshift)
        if di.field_number == 29:
            self.flight_stage |= bp.int32((int(b) << lshift))
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 1:
            return (self.cur_time >> rshift) & 255
        if di.field_number == 2:
            return (self.gps_lat >> rshift) & 255
        if di.field_number == 3:
            return (self.gps_lng >> rshift) & 255
        if di.field_number == 4:
            return (self.gps_alt >> rshift) & 255
        if di.field_number == 5:
            return (self.accel_x >> rshift) & 255
        if di.field_number == 6:
            return (self.accel_y >> rshift) & 255
        if di.field_number == 7:
            return (self.accel_z >> rshift) & 255
        if di.field_number == 8:
            return (self.gyro_x >> rshift) & 255
        if di.field_number == 9:
            return (self.gyro_y >> rshift) & 255
        if di.field_number == 10:
            return (self.gyro_z >> rshift) & 255
        if di.field_number == 11:
            return (self.hg_accel >> rshift) & 255
        if di.field_number == 12:
            return (self.alt_baro >> rshift) & 255
        if di.field_number == 13:
            return (self.vel_vertical >> rshift) & 255
        if di.field_number == 14:
            return (self.smooth_vel >> rshift) & 255
        if di.field_number == 15:
            return (self.press >> rshift) & 255
        if di.field_number == 16:
            return (self.temp >> rshift) & 255
        if di.field_number == 17:
            return (self.launchsite_msl >> rshift) & 255
        if di.field_number == 18:
            return (int(self.airbrake_cont) >> rshift) & 255
        if di.field_number == 19:
            return (self.ab_servo_pct >> rshift) & 255
        if di.field_number == 20:
            return (self.cnrd_servo_pct >> rshift) & 255
        if di.field_number == 21:
            return (int(self.drogue_pyro_cont_1) >> rshift) & 255
        if di.field_number == 22:
            return (int(self.drogue_pyro_cont_2) >> rshift) & 255
        if di.field_number == 23:
            return (int(self.main_pyro_cont_1) >> rshift) & 255
        if di.field_number == 24:
            return (int(self.main_pyro_cont_2) >> rshift) & 255
        if di.field_number == 25:
            return (self.flight_index >> rshift) & 255
        if di.field_number == 26:
            return (int(self.ellipse_on) >> rshift) & 255
        if di.field_number == 27:
            return (int(self.cameras_on) >> rshift) & 255
        if di.field_number == 28:
            return (self.battery_voltage >> rshift) & 255
        if di.field_number == 29:
            return (self.flight_stage >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return