/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "telemetry.pb.h"
#include "pb_common.h"
#include "pb_encode.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif



PB_BIND(rocket_telemetry_TelemetryPacket, rocket_telemetry_TelemetryPacket, AUTO)
