// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__TELEMETRY_BP_H__
#define __BITPROTO__TELEMETRY_BP_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct TelemetryPacket
#define BYTES_LENGTH_TELEMETRY_PACKET 89

struct TelemetryPacket {
    // 1. Time
    uint32_t cur_time; // 32bit
    // 2. GPS
    int32_t gps_lat; // 32bit
    // Scaled by 10^7
    int32_t gps_lng; // 32bit
    // Scaled by 10^7
    int32_t gps_alt; // 32bit
    uint32_t accel_x; // 32bit
    uint32_t accel_y; // 32bit
    uint32_t accel_z; // 32bit
    uint32_t gyro_x; // 32bit
    uint32_t gyro_y; // 32bit
    uint32_t gyro_z; // 32bit
    uint32_t hg_accel; // 32bit
    // 4. Flight Data
    uint32_t alt_baro; // 32bit
    uint32_t vel_vertical; // 32bit
    uint32_t smooth_vel; // 32bit
    uint32_t press; // 32bit
    uint32_t temp; // 32bit
    uint32_t launchsite_msl; // 32bit
    // 5. Servos & Continuity
    bool airbrake_cont; // 1bit
    uint32_t ab_servo_pct; // 32bit
    uint32_t cnrd_servo_pct; // 32bit
    bool drogue_pyro_cont_1; // 1bit
    bool drogue_pyro_cont_2; // 1bit
    bool main_pyro_cont_1; // 1bit
    bool main_pyro_cont_2; // 1bit
    // 6. State & Status
    int32_t flight_index; // 32bit
    bool ellipse_on; // 1bit
    bool cameras_on; // 1bit
    uint32_t battery_voltage; // 32bit
    int32_t flight_stage; // 32bit
};

// Encode struct TelemetryPacket to given buffer s.
int EncodeTelemetryPacket(struct TelemetryPacket *m, unsigned char *s);
// Decode struct TelemetryPacket from given buffer s.
int DecodeTelemetryPacket(struct TelemetryPacket *m, unsigned char *s);
// Format struct TelemetryPacket to a json format string.
int JsonTelemetryPacket(struct TelemetryPacket *m, char *s);

void BpXXXProcessTelemetryPacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatTelemetryPacket(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif