/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROCKET_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#define PB_ROCKET_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* TelemetryPacket matches the exact fields from the CSV format for easy migration. */
typedef struct _rocket_telemetry_TelemetryPacket {
    /* 1. Time (0) */
    uint32_t cur_time;
    /* 2. GPS (1-3) */
    int32_t gps_lat;
    int32_t gps_lng;
    int32_t gps_alt;
    /* 3. IMU (4-10) */
    float accel_x; /* accel[0] */
    float accel_y;
    float accel_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
    float hg_accel; /* hg_accel[0] */
    /* 4. Flight Data (11-16) */
    float alt_baro; /* alt[0] */
    float vel_vertical; /* vel[0] */
    float smooth_vel;
    float press;
    float temp;
    float launchsite_msl;
    /* 5. Servos & Continuity (17-23) */
    bool airbrake_cont;
    float ab_servo_pct;
    float cnrd_servo_pct;
    bool drogue_pyro_cont_1;
    bool drogue_pyro_cont_2;
    bool main_pyro_cont_1;
    bool main_pyro_cont_2;
    /* 6. State & Status (24-28) */
    int32_t flight_index;
    bool ellipse_on;
    bool cameras_on;
    float battery_voltage;
    int32_t flight_stage;
} rocket_telemetry_TelemetryPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rocket_telemetry_TelemetryPacket_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rocket_telemetry_TelemetryPacket_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rocket_telemetry_TelemetryPacket_cur_time_tag 1
#define rocket_telemetry_TelemetryPacket_gps_lat_tag 2
#define rocket_telemetry_TelemetryPacket_gps_lng_tag 3
#define rocket_telemetry_TelemetryPacket_gps_alt_tag 4
#define rocket_telemetry_TelemetryPacket_accel_x_tag 5
#define rocket_telemetry_TelemetryPacket_accel_y_tag 6
#define rocket_telemetry_TelemetryPacket_accel_z_tag 7
#define rocket_telemetry_TelemetryPacket_gyro_x_tag 8
#define rocket_telemetry_TelemetryPacket_gyro_y_tag 9
#define rocket_telemetry_TelemetryPacket_gyro_z_tag 10
#define rocket_telemetry_TelemetryPacket_hg_accel_tag 11
#define rocket_telemetry_TelemetryPacket_alt_baro_tag 12
#define rocket_telemetry_TelemetryPacket_vel_vertical_tag 13
#define rocket_telemetry_TelemetryPacket_smooth_vel_tag 14
#define rocket_telemetry_TelemetryPacket_press_tag 15
#define rocket_telemetry_TelemetryPacket_temp_tag 16
#define rocket_telemetry_TelemetryPacket_launchsite_msl_tag 17
#define rocket_telemetry_TelemetryPacket_airbrake_cont_tag 18
#define rocket_telemetry_TelemetryPacket_ab_servo_pct_tag 19
#define rocket_telemetry_TelemetryPacket_cnrd_servo_pct_tag 20
#define rocket_telemetry_TelemetryPacket_drogue_pyro_cont_1_tag 21
#define rocket_telemetry_TelemetryPacket_drogue_pyro_cont_2_tag 22
#define rocket_telemetry_TelemetryPacket_main_pyro_cont_1_tag 23
#define rocket_telemetry_TelemetryPacket_main_pyro_cont_2_tag 24
#define rocket_telemetry_TelemetryPacket_flight_index_tag 25
#define rocket_telemetry_TelemetryPacket_ellipse_on_tag 26
#define rocket_telemetry_TelemetryPacket_cameras_on_tag 27
#define rocket_telemetry_TelemetryPacket_battery_voltage_tag 28
#define rocket_telemetry_TelemetryPacket_flight_stage_tag 29

/* Struct field encoding specification for nanopb */
#define rocket_telemetry_TelemetryPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cur_time,          1) \
X(a, STATIC,   SINGULAR, INT32,    gps_lat,           2) \
X(a, STATIC,   SINGULAR, INT32,    gps_lng,           3) \
X(a, STATIC,   SINGULAR, INT32,    gps_alt,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,            8) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,            9) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,           10) \
X(a, STATIC,   SINGULAR, FLOAT,    hg_accel,         11) \
X(a, STATIC,   SINGULAR, FLOAT,    alt_baro,         12) \
X(a, STATIC,   SINGULAR, FLOAT,    vel_vertical,     13) \
X(a, STATIC,   SINGULAR, FLOAT,    smooth_vel,       14) \
X(a, STATIC,   SINGULAR, FLOAT,    press,            15) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,             16) \
X(a, STATIC,   SINGULAR, FLOAT,    launchsite_msl,   17) \
X(a, STATIC,   SINGULAR, BOOL,     airbrake_cont,    18) \
X(a, STATIC,   SINGULAR, FLOAT,    ab_servo_pct,     19) \
X(a, STATIC,   SINGULAR, FLOAT,    cnrd_servo_pct,   20) \
X(a, STATIC,   SINGULAR, BOOL,     drogue_pyro_cont_1,  21) \
X(a, STATIC,   SINGULAR, BOOL,     drogue_pyro_cont_2,  22) \
X(a, STATIC,   SINGULAR, BOOL,     main_pyro_cont_1,  23) \
X(a, STATIC,   SINGULAR, BOOL,     main_pyro_cont_2,  24) \
X(a, STATIC,   SINGULAR, INT32,    flight_index,     25) \
X(a, STATIC,   SINGULAR, BOOL,     ellipse_on,       26) \
X(a, STATIC,   SINGULAR, BOOL,     cameras_on,       27) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,  28) \
X(a, STATIC,   SINGULAR, INT32,    flight_stage,     29)
#define rocket_telemetry_TelemetryPacket_CALLBACK NULL
#define rocket_telemetry_TelemetryPacket_DEFAULT NULL

extern const pb_msgdesc_t rocket_telemetry_TelemetryPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rocket_telemetry_TelemetryPacket_fields &rocket_telemetry_TelemetryPacket_msg

/* Maximum encoded size of messages (where known) */
#define ROCKET_TELEMETRY_TELEMETRY_PB_H_MAX_SIZE rocket_telemetry_TelemetryPacket_size
#define rocket_telemetry_TelemetryPacket_size    169

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
