// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "telemetry_bp.h"

void BpFieldDescriptorsInitTelemetryPacket(struct TelemetryPacket *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->cur_time), BpUint(32, sizeof(uint32_t)), "cur_time");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->gps_lat), BpInt(32, sizeof(int32_t)), "gps_lat");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->gps_lng), BpInt(32, sizeof(int32_t)), "gps_lng");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->gps_alt), BpInt(32, sizeof(int32_t)), "gps_alt");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->accel_x), BpUint(32, sizeof(uint32_t)), "accel_x");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->accel_y), BpUint(32, sizeof(uint32_t)), "accel_y");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->accel_z), BpUint(32, sizeof(uint32_t)), "accel_z");
    fds[7] = BpMessageFieldDescriptor((void *)&(m->gyro_x), BpUint(32, sizeof(uint32_t)), "gyro_x");
    fds[8] = BpMessageFieldDescriptor((void *)&(m->gyro_y), BpUint(32, sizeof(uint32_t)), "gyro_y");
    fds[9] = BpMessageFieldDescriptor((void *)&(m->gyro_z), BpUint(32, sizeof(uint32_t)), "gyro_z");
    fds[10] = BpMessageFieldDescriptor((void *)&(m->hg_accel), BpUint(32, sizeof(uint32_t)), "hg_accel");
    fds[11] = BpMessageFieldDescriptor((void *)&(m->alt_baro), BpUint(32, sizeof(uint32_t)), "alt_baro");
    fds[12] = BpMessageFieldDescriptor((void *)&(m->vel_vertical), BpUint(32, sizeof(uint32_t)), "vel_vertical");
    fds[13] = BpMessageFieldDescriptor((void *)&(m->smooth_vel), BpUint(32, sizeof(uint32_t)), "smooth_vel");
    fds[14] = BpMessageFieldDescriptor((void *)&(m->press), BpUint(32, sizeof(uint32_t)), "press");
    fds[15] = BpMessageFieldDescriptor((void *)&(m->temp), BpUint(32, sizeof(uint32_t)), "temp");
    fds[16] = BpMessageFieldDescriptor((void *)&(m->launchsite_msl), BpUint(32, sizeof(uint32_t)), "launchsite_msl");
    fds[17] = BpMessageFieldDescriptor((void *)&(m->airbrake_cont), BpBool(), "airbrake_cont");
    fds[18] = BpMessageFieldDescriptor((void *)&(m->ab_servo_pct), BpUint(32, sizeof(uint32_t)), "ab_servo_pct");
    fds[19] = BpMessageFieldDescriptor((void *)&(m->cnrd_servo_pct), BpUint(32, sizeof(uint32_t)), "cnrd_servo_pct");
    fds[20] = BpMessageFieldDescriptor((void *)&(m->drogue_pyro_cont_1), BpBool(), "drogue_pyro_cont_1");
    fds[21] = BpMessageFieldDescriptor((void *)&(m->drogue_pyro_cont_2), BpBool(), "drogue_pyro_cont_2");
    fds[22] = BpMessageFieldDescriptor((void *)&(m->main_pyro_cont_1), BpBool(), "main_pyro_cont_1");
    fds[23] = BpMessageFieldDescriptor((void *)&(m->main_pyro_cont_2), BpBool(), "main_pyro_cont_2");
    fds[24] = BpMessageFieldDescriptor((void *)&(m->flight_index), BpInt(32, sizeof(int32_t)), "flight_index");
    fds[25] = BpMessageFieldDescriptor((void *)&(m->ellipse_on), BpBool(), "ellipse_on");
    fds[26] = BpMessageFieldDescriptor((void *)&(m->cameras_on), BpBool(), "cameras_on");
    fds[27] = BpMessageFieldDescriptor((void *)&(m->battery_voltage), BpUint(32, sizeof(uint32_t)), "battery_voltage");
    fds[28] = BpMessageFieldDescriptor((void *)&(m->flight_stage), BpInt(32, sizeof(int32_t)), "flight_stage");
}

void BpXXXProcessTelemetryPacket(void *data, struct BpProcessorContext *ctx) {
    struct TelemetryPacket *m = (struct TelemetryPacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[29];
    BpFieldDescriptorsInitTelemetryPacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 29, 711, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatTelemetryPacket(void *data, struct BpJsonFormatContext *ctx) {
    struct TelemetryPacket *m = (struct TelemetryPacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[29];
    BpFieldDescriptorsInitTelemetryPacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 29, 711, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeTelemetryPacket(struct TelemetryPacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessTelemetryPacket((void *)m, &ctx);
    return 0;
}

int DecodeTelemetryPacket(struct TelemetryPacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessTelemetryPacket((void *)m, &ctx);
    return 0;
}

int JsonTelemetryPacket(struct TelemetryPacket *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatTelemetryPacket((void *)m, &ctx);
    return ctx.n;
}